/**
 ******************************************************************************
 * @file           : fender.c
 * @brief          : Run-Length Encoded font data and lookup table for the fender font.
 * This file was automatically generated by the font converter with source font: fender.
 ******************************************************************************
*/

/* Includes ------------------------------------------------------------------*/
#include "fender_font.h"

/* Private Variables ---------------------------------------------------------*/
const Font_t font_fender = {
    .name = "fender",
    .lookup_table = fender_lookup,
    .table_size = 95,
    .rle_data = font_fender_rle_data,
};

const Charachter_Font_t fender_lookup[] = {
	{.start_offset_rle = 0, .end_offset_rle = 2, .col_width = 3, .row_height = 5},
	{.start_offset_rle = 2, .end_offset_rle = 24, .col_width = 3, .row_height = 7},
	{.start_offset_rle = 24, .end_offset_rle = 30, .col_width = 5, .row_height = 1},
	{.start_offset_rle = 30, .end_offset_rle = 64, .col_width = 5, .row_height = 5},
	{.start_offset_rle = 64, .end_offset_rle = 126, .col_width = 7, .row_height = 5},
	{.start_offset_rle = 126, .end_offset_rle = 178, .col_width = 6, .row_height = 7},
	{.start_offset_rle = 178, .end_offset_rle = 228, .col_width = 6, .row_height = 5},
	{.start_offset_rle = 228, .end_offset_rle = 230, .col_width = 2, .row_height = 1},
	{.start_offset_rle = 230, .end_offset_rle = 258, .col_width = 3, .row_height = 5},
	{.start_offset_rle = 258, .end_offset_rle = 286, .col_width = 3, .row_height = 5},
	{.start_offset_rle = 286, .end_offset_rle = 322, .col_width = 5, .row_height = 4},
	{.start_offset_rle = 322, .end_offset_rle = 356, .col_width = 5, .row_height = 6},
	{.start_offset_rle = 356, .end_offset_rle = 358, .col_width = 2, .row_height = 1},
	{.start_offset_rle = 358, .end_offset_rle = 372, .col_width = 3, .row_height = 5},
	{.start_offset_rle = 372, .end_offset_rle = 374, .col_width = 2, .row_height = 1},
	{.start_offset_rle = 374, .end_offset_rle = 400, .col_width = 6, .row_height = 5},
	{.start_offset_rle = 400, .end_offset_rle = 430, .col_width = 5, .row_height = 5},
	{.start_offset_rle = 430, .end_offset_rle = 460, .col_width = 4, .row_height = 5},
	{.start_offset_rle = 460, .end_offset_rle = 492, .col_width = 5, .row_height = 5},
	{.start_offset_rle = 492, .end_offset_rle = 522, .col_width = 6, .row_height = 5},
	{.start_offset_rle = 522, .end_offset_rle = 560, .col_width = 8, .row_height = 5},
	{.start_offset_rle = 560, .end_offset_rle = 584, .col_width = 6, .row_height = 5},
	{.start_offset_rle = 584, .end_offset_rle = 620, .col_width = 6, .row_height = 5},
	{.start_offset_rle = 620, .end_offset_rle = 646, .col_width = 6, .row_height = 5},
	{.start_offset_rle = 646, .end_offset_rle = 688, .col_width = 7, .row_height = 5},
	{.start_offset_rle = 688, .end_offset_rle = 722, .col_width = 7, .row_height = 5},
	{.start_offset_rle = 722, .end_offset_rle = 740, .col_width = 5, .row_height = 6},
	{.start_offset_rle = 740, .end_offset_rle = 750, .col_width = 2, .row_height = 4},
	{.start_offset_rle = 750, .end_offset_rle = 774, .col_width = 4, .row_height = 5},
	{.start_offset_rle = 774, .end_offset_rle = 780, .col_width = 3, .row_height = 3},
	{.start_offset_rle = 780, .end_offset_rle = 804, .col_width = 4, .row_height = 5},
	{.start_offset_rle = 804, .end_offset_rle = 838, .col_width = 7, .row_height = 5},
	{.start_offset_rle = 838, .end_offset_rle = 874, .col_width = 5, .row_height = 5},
	{.start_offset_rle = 874, .end_offset_rle = 924, .col_width = 13, .row_height = 5},
	{.start_offset_rle = 924, .end_offset_rle = 968, .col_width = 8, .row_height = 5},
	{.start_offset_rle = 968, .end_offset_rle = 996, .col_width = 7, .row_height = 5},
	{.start_offset_rle = 996, .end_offset_rle = 1040, .col_width = 8, .row_height = 5},
	{.start_offset_rle = 1040, .end_offset_rle = 1082, .col_width = 8, .row_height = 5},
	{.start_offset_rle = 1082, .end_offset_rle = 1124, .col_width = 8, .row_height = 5},
	{.start_offset_rle = 1124, .end_offset_rle = 1166, .col_width = 8, .row_height = 5},
	{.start_offset_rle = 1166, .end_offset_rle = 1216, .col_width = 8, .row_height = 5},
	{.start_offset_rle = 1216, .end_offset_rle = 1254, .col_width = 8, .row_height = 5},
	{.start_offset_rle = 1254, .end_offset_rle = 1292, .col_width = 8, .row_height = 5},
	{.start_offset_rle = 1292, .end_offset_rle = 1340, .col_width = 8, .row_height = 5},
	{.start_offset_rle = 1340, .end_offset_rle = 1372, .col_width = 7, .row_height = 5},
	{.start_offset_rle = 1372, .end_offset_rle = 1430, .col_width = 11, .row_height = 5},
	{.start_offset_rle = 1430, .end_offset_rle = 1492, .col_width = 10, .row_height = 5},
	{.start_offset_rle = 1492, .end_offset_rle = 1530, .col_width = 8, .row_height = 5},
	{.start_offset_rle = 1530, .end_offset_rle = 1570, .col_width = 8, .row_height = 5},
	{.start_offset_rle = 1570, .end_offset_rle = 1618, .col_width = 9, .row_height = 5},
	{.start_offset_rle = 1618, .end_offset_rle = 1666, .col_width = 8, .row_height = 5},
	{.start_offset_rle = 1666, .end_offset_rle = 1708, .col_width = 7, .row_height = 5},
	{.start_offset_rle = 1708, .end_offset_rle = 1746, .col_width = 8, .row_height = 5},
	{.start_offset_rle = 1746, .end_offset_rle = 1800, .col_width = 9, .row_height = 5},
	{.start_offset_rle = 1800, .end_offset_rle = 1842, .col_width = 10, .row_height = 5},
	{.start_offset_rle = 1842, .end_offset_rle = 1904, .col_width = 12, .row_height = 5},
	{.start_offset_rle = 1904, .end_offset_rle = 1948, .col_width = 8, .row_height = 5},
	{.start_offset_rle = 1948, .end_offset_rle = 1988, .col_width = 8, .row_height = 5},
	{.start_offset_rle = 1988, .end_offset_rle = 2018, .col_width = 7, .row_height = 5},
	{.start_offset_rle = 2018, .end_offset_rle = 2038, .col_width = 5, .row_height = 5},
	{.start_offset_rle = 2038, .end_offset_rle = 2064, .col_width = 6, .row_height = 5},
	{.start_offset_rle = 2064, .end_offset_rle = 2084, .col_width = 5, .row_height = 5},
	{.start_offset_rle = 2084, .end_offset_rle = 2106, .col_width = 5, .row_height = 3},
	{.start_offset_rle = 2106, .end_offset_rle = 2108, .col_width = 0, .row_height = 0},
	{.start_offset_rle = 2108, .end_offset_rle = 2112, .col_width = 4, .row_height = 3},
	{.start_offset_rle = 2112, .end_offset_rle = 2142, .col_width = 7, .row_height = 3},
	{.start_offset_rle = 2142, .end_offset_rle = 2182, .col_width = 7, .row_height = 5},
	{.start_offset_rle = 2182, .end_offset_rle = 2202, .col_width = 5, .row_height = 3},
	{.start_offset_rle = 2202, .end_offset_rle = 2242, .col_width = 7, .row_height = 5},
	{.start_offset_rle = 2242, .end_offset_rle = 2266, .col_width = 6, .row_height = 3},
	{.start_offset_rle = 2266, .end_offset_rle = 2306, .col_width = 5, .row_height = 5},
	{.start_offset_rle = 2306, .end_offset_rle = 2328, .col_width = 6, .row_height = 3},
	{.start_offset_rle = 2328, .end_offset_rle = 2386, .col_width = 7, .row_height = 7},
	{.start_offset_rle = 2384, .end_offset_rle = 2408, .col_width = 4, .row_height = 4},
	{.start_offset_rle = 2408, .end_offset_rle = 2424, .col_width = 5, .row_height = 4},
	{.start_offset_rle = 2424, .end_offset_rle = 2480, .col_width = 7, .row_height = 7},
	{.start_offset_rle = 2480, .end_offset_rle = 2510, .col_width = 4, .row_height = 5},
	{.start_offset_rle = 2510, .end_offset_rle = 2550, .col_width = 10, .row_height = 3},
	{.start_offset_rle = 2550, .end_offset_rle = 2582, .col_width = 8, .row_height = 3},
	{.start_offset_rle = 2582, .end_offset_rle = 2608, .col_width = 6, .row_height = 3},
	{.start_offset_rle = 2608, .end_offset_rle = 2636, .col_width = 7, .row_height = 3},
	{.start_offset_rle = 2636, .end_offset_rle = 2680, .col_width = 7, .row_height = 7},
	{.start_offset_rle = 2680, .end_offset_rle = 2724, .col_width = 8, .row_height = 7},
	{.start_offset_rle = 2724, .end_offset_rle = 2742, .col_width = 5, .row_height = 3},
	{.start_offset_rle = 2742, .end_offset_rle = 2778, .col_width = 7, .row_height = 5},
	{.start_offset_rle = 2778, .end_offset_rle = 2812, .col_width = 8, .row_height = 3},
	{.start_offset_rle = 2812, .end_offset_rle = 2834, .col_width = 6, .row_height = 3},
	{.start_offset_rle = 2834, .end_offset_rle = 2868, .col_width = 10, .row_height = 3},
	{.start_offset_rle = 2868, .end_offset_rle = 2888, .col_width = 6, .row_height = 3},
	{.start_offset_rle = 2888, .end_offset_rle = 2916, .col_width = 8, .row_height = 3},
	{.start_offset_rle = 2916, .end_offset_rle = 2954, .col_width = 7, .row_height = 7},
	{.start_offset_rle = 2954, .end_offset_rle = 2978, .col_width = 4, .row_height = 5},
	{.start_offset_rle = 2978, .end_offset_rle = 2988, .col_width = 2, .row_height = 5},
	{.start_offset_rle = 2988, .end_offset_rle = 3018, .col_width = 4, .row_height = 7},
	{.start_offset_rle = 3018, .end_offset_rle = 3034, .col_width = 4, .row_height = 2},
};

const uint16_t font_fender_rle_data[] = {
    // --- ' ' (Offset 0) ---
 	15, ASCII_SPACE,

    // --- '!' (Offset 2) ---
 	3, ASCII_SPACE, 3, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE,
 	3, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE,

    // --- '"' (Offset 24) ---
 	2, ASCII_SINGLE_QUOTE, 1, ASCII_SPACE, 2, ASCII_SINGLE_QUOTE,

    // --- '#' (Offset 30) ---
 	1, ASCII_SPACE, 1, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_PIPE,
 	1, ASCII_SPACE, 5, ASCII_SINGLE_QUOTE, 1, ASCII_SPACE, 1, ASCII_PIPE,
 	1, ASCII_SPACE, 1, ASCII_PIPE, 1, ASCII_SPACE, 5, ASCII_SINGLE_QUOTE,
 	1, ASCII_SPACE, 1, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_PIPE,
 	1, ASCII_SPACE,

    // --- '$' (Offset 64) ---
 	2, ASCII_SPACE, 1, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_PIPE,
 	2, ASCII_SPACE, 1, ASCII_DOT, 1, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE, 1, ASCII_SPACE,
 	1, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_PIPE, 1, ASCII_SPACE,
 	1, ASCII_PIPE, 2, ASCII_SPACE, 1, ASCII_SPACE, 1, ASCII_BACKTICK,
 	1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE, 1, ASCII_COMMA,
 	1, ASCII_SPACE, 2, ASCII_SPACE, 1, ASCII_PIPE, 1, ASCII_SPACE,
 	1, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_PIPE,

    // --- '%' (Offset 126) ---
 	1, ASCII_SPACE, 1, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE,
 	1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE, 2, ASCII_SPACE, 1, ASCII_PIPE,
 	1, ASCII_SPACE, 1, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_BACKTICK,
 	3, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_SPACE, 2, ASCII_SPACE, 2, ASCII_PIPE, 2, ASCII_SPACE,
 	1, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_PIPE,
 	3, ASCII_SPACE, 1, ASCII_COMMA,

    // --- '&' (Offset 178) ---
 	1, ASCII_DOT, 2, ASCII_SINGLE_QUOTE, 1, ASCII_COMMA, 2, ASCII_SPACE,
 	1, ASCII_PIPE, 2, ASCII_SPACE, 1, ASCII_PIPE, 2, ASCII_SPACE,
 	1, ASCII_DOT, 1, ASCII_BACKTICK, 1, ASCII_SINGLE_QUOTE, 1, ASCII_COMMA,
 	1, ASCII_SPACE, 1, ASCII_COMMA, 1, ASCII_PIPE, 1, ASCII_SPACE,
 	1, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_PIPE, 1, ASCII_SPACE,
 	1, ASCII_BACKTICK, 2, ASCII_COMMA, 1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE,
 	1, ASCII_SPACE,

    // --- ''' (Offset 228) ---
 	2, ASCII_SINGLE_QUOTE,

    // --- '(' (Offset 230) ---
 	1, ASCII_SPACE, 1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_SINGLE_QUOTE, 1, ASCII_SPACE, 1, ASCII_PIPE, 2, ASCII_SPACE,
 	1, ASCII_PIPE, 1, ASCII_COMMA, 1, ASCII_SPACE, 1, ASCII_SPACE,
 	1, ASCII_PIPE, 1, ASCII_DOT,

    // --- ')' (Offset 258) ---
 	1, ASCII_BACKTICK, 1, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_SPACE,
 	1, ASCII_BACKTICK, 1, ASCII_PIPE, 2, ASCII_SPACE, 1, ASCII_PIPE,
 	1, ASCII_SPACE, 1, ASCII_COMMA, 1, ASCII_PIPE, 1, ASCII_DOT,
 	1, ASCII_PIPE, 1, ASCII_SPACE,

    // --- '*' (Offset 286) ---
 	1, ASCII_COMMA, 1, ASCII_SPACE, 1, ASCII_PIPE, 1, ASCII_SPACE,
 	1, ASCII_COMMA, 1, ASCII_SPACE, 1, ASCII_COMMA, 1, ASCII_PIPE,
 	1, ASCII_COMMA, 1, ASCII_SPACE, 2, ASCII_HYPHEN, 1, ASCII_PIPE,
 	2, ASCII_HYPHEN, 1, ASCII_SPACE, 1, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_SINGLE_QUOTE, 1, ASCII_SPACE,

    // --- '+' (Offset 322) ---
 	1, ASCII_SINGLE_QUOTE, 1, ASCII_SPACE, 1, ASCII_PIPE, 1, ASCII_SPACE,
 	1, ASCII_SINGLE_QUOTE, 5, ASCII_SPACE, 5, ASCII_SPACE, 1, ASCII_SPACE,
 	1, ASCII_PIPE, 3, ASCII_SPACE, 1, ASCII_HYPHEN, 1, ASCII_PIPE,
 	1, ASCII_HYPHEN, 2, ASCII_SPACE, 1, ASCII_SPACE, 1, ASCII_PIPE,
 	3, ASCII_SPACE,

    // --- ',' (Offset 356) ---
 	2, ASCII_COMMA,

    // --- '-' (Offset 358) ---
 	1, ASCII_SPACE, 1, ASCII_COMMA, 1, ASCII_SPACE, 3, ASCII_SPACE,
 	3, ASCII_SPACE, 3, ASCII_SPACE, 3, ASCII_HYPHEN,

    // --- '.' (Offset 372) ---
 	2, ASCII_DOT,

    // --- '/' (Offset 374) ---
 	4, ASCII_SPACE, 2, ASCII_SINGLE_QUOTE, 3, ASCII_SPACE, 2, ASCII_SINGLE_QUOTE,
 	1, ASCII_SPACE, 2, ASCII_SPACE, 2, ASCII_SINGLE_QUOTE, 2, ASCII_SPACE,
 	1, ASCII_SPACE, 2, ASCII_SINGLE_QUOTE, 3, ASCII_SPACE, 2, ASCII_SINGLE_QUOTE,
 	4, ASCII_SPACE,

    // --- '0' (Offset 400) ---
 	1, ASCII_DOT, 3, ASCII_SINGLE_QUOTE, 1, ASCII_COMMA, 1, ASCII_PIPE,
 	3, ASCII_SPACE, 1, ASCII_PIPE, 1, ASCII_PIPE, 3, ASCII_SPACE,
 	1, ASCII_PIPE, 1, ASCII_PIPE, 3, ASCII_SPACE, 1, ASCII_PIPE,
 	1, ASCII_BACKTICK, 3, ASCII_COMMA, 1, ASCII_SINGLE_QUOTE,

    // --- '1' (Offset 430) ---
 	1, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_SINGLE_QUOTE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE,
 	1, ASCII_DOT, 2, ASCII_PIPE, 1, ASCII_DOT,

    // --- '2' (Offset 460) ---
 	1, ASCII_SPACE, 2, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE, 1, ASCII_COMMA,
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_SPACE, 2, ASCII_PIPE, 2, ASCII_SPACE,
 	1, ASCII_DOT, 1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE, 1, ASCII_SPACE,
 	2, ASCII_SLASH, 2, ASCII_SPACE, 2, ASCII_OPEN_PAREN, 3, ASCII_DOT,

    // --- '3' (Offset 492) ---
 	1, ASCII_COMMA, 3, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE, 1, ASCII_COMMA,
 	4, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE, 3, ASCII_SINGLE_QUOTE,
 	2, ASCII_PIPE, 4, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE,
 	3, ASCII_DOT, 1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE,

    // --- '4' (Offset 522) ---
 	3, ASCII_SPACE, 1, ASCII_SLASH, 2, ASCII_PIPE, 2, ASCII_SPACE,
 	1, ASCII_SPACE, 2, ASCII_SLASH, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	2, ASCII_SPACE, 2, ASCII_SLASH, 2, ASCII_DOT, 2, ASCII_PIPE,
 	2, ASCII_DOT, 4, ASCII_SPACE, 2, ASCII_PIPE, 2, ASCII_SPACE,
 	4, ASCII_SPACE, 2, ASCII_PIPE, 2, ASCII_SPACE,

    // --- '5' (Offset 560) ---
 	2, ASCII_PIPE, 4, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 4, ASCII_SPACE,
 	1, ASCII_BACKTICK, 3, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 4, ASCII_SPACE,
 	2, ASCII_PIPE, 4, ASCII_DOT, 1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE,

    // --- '6' (Offset 584) ---
 	1, ASCII_SPACE, 4, ASCII_COMMA, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	3, ASCII_SPACE, 1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE,
 	1, ASCII_PIPE, 1, ASCII_COMMA, 2, ASCII_PIPE, 2, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_BACKTICK, 1, ASCII_PIPE, 2, ASCII_DOT,
 	1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE,

    // --- '7' (Offset 620) ---
 	5, ASCII_SINGLE_QUOTE, 1, ASCII_SLASH, 3, ASCII_SPACE, 2, ASCII_SLASH,
 	1, ASCII_SPACE, 2, ASCII_SPACE, 2, ASCII_SLASH, 2, ASCII_SPACE,
 	1, ASCII_SPACE, 2, ASCII_SLASH, 3, ASCII_SPACE, 2, ASCII_SLASH,
 	4, ASCII_SPACE,

    // --- '8' (Offset 646) ---
 	1, ASCII_DOT, 1, ASCII_PIPE, 3, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_COMMA, 2, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_SPACE, 2, ASCII_CLOSE_PAREN, 1, ASCII_HYPHEN, 2, ASCII_OPEN_PAREN,
 	1, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_BACKTICK, 1, ASCII_PIPE, 3, ASCII_DOT, 1, ASCII_PIPE,
 	1, ASCII_SINGLE_QUOTE,

    // --- '9' (Offset 688) ---
 	1, ASCII_DOT, 1, ASCII_PIPE, 3, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_COMMA, 2, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_BACKTICK, 1, ASCII_PIPE, 3, ASCII_DOT, 2, ASCII_PIPE,
 	5, ASCII_SPACE, 2, ASCII_SINGLE_QUOTE, 4, ASCII_SPACE, 2, ASCII_SINGLE_QUOTE,
 	1, ASCII_SPACE,

    // --- ':' (Offset 722) ---
 	3, ASCII_SPACE, 2, ASCII_SINGLE_QUOTE, 5, ASCII_SPACE, 5, ASCII_SPACE,
 	2, ASCII_PIPE, 3, ASCII_SPACE, 5, ASCII_SPACE, 2, ASCII_PIPE,
 	3, ASCII_SPACE,

    // --- ';' (Offset 740) ---
 	2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE,
 	1, ASCII_SINGLE_QUOTE,

    // --- '<' (Offset 750) ---
 	2, ASCII_SPACE, 2, ASCII_COMMA, 1, ASCII_SPACE, 2, ASCII_COMMA,
 	1, ASCII_SPACE, 2, ASCII_COMMA, 2, ASCII_SPACE, 1, ASCII_SPACE,
 	2, ASCII_COMMA, 1, ASCII_SPACE, 2, ASCII_SPACE, 2, ASCII_COMMA,

    // --- '=' (Offset 774) ---
 	3, ASCII_COMMA, 3, ASCII_SPACE, 3, ASCII_SINGLE_QUOTE,

    // --- '>' (Offset 780) ---
 	2, ASCII_COMMA, 2, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_COMMA,
 	1, ASCII_SPACE, 2, ASCII_SPACE, 2, ASCII_COMMA, 1, ASCII_SPACE,
 	2, ASCII_COMMA, 1, ASCII_SPACE, 2, ASCII_COMMA, 2, ASCII_SPACE,

    // --- '?' (Offset 804) ---
 	1, ASCII_DOT, 1, ASCII_PIPE, 3, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_COMMA, 2, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_PIPE,
 	4, ASCII_SPACE, 2, ASCII_SLASH, 1, ASCII_SINGLE_QUOTE, 3, ASCII_SPACE,
 	2, ASCII_PIPE, 2, ASCII_SPACE, 3, ASCII_SPACE, 2, ASCII_DOT,
 	2, ASCII_SPACE,

    // --- '@' (Offset 838) ---
 	1, ASCII_DOT, 3, ASCII_SINGLE_QUOTE, 1, ASCII_COMMA, 1, ASCII_PIPE,
 	1, ASCII_SPACE, 1, ASCII_DOT, 1, ASCII_SPACE, 1, ASCII_PIPE,
 	1, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_PIPE, 1, ASCII_COMMA,
 	1, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE, 4, ASCII_SPACE, 1, ASCII_BACKTICK,
 	3, ASCII_DOT, 1, ASCII_SPACE,

    // --- 'A' (Offset 874) ---
 	5, ASCII_SPACE, 1, ASCII_SLASH, 1, ASCII_DOT, 1, ASCII_BACKSLASH,
 	5, ASCII_SPACE, 4, ASCII_SPACE, 2, ASCII_SLASH, 1, ASCII_SPACE,
 	2, ASCII_BACKSLASH, 4, ASCII_SPACE, 3, ASCII_SPACE, 2, ASCII_SLASH,
 	3, ASCII_DOT, 2, ASCII_BACKSLASH, 3, ASCII_SPACE, 2, ASCII_SPACE,
 	2, ASCII_SLASH, 5, ASCII_SPACE, 2, ASCII_BACKSLASH, 2, ASCII_SPACE,
 	1, ASCII_DOT, 2, ASCII_SLASH, 7, ASCII_SPACE, 2, ASCII_BACKSLASH,
 	1, ASCII_DOT,

    // --- 'B' (Offset 924) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 3, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_COMMA, 1, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 2, ASCII_PIPE, 4, ASCII_SEMICOLON,
 	1, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_DOT, 2, ASCII_PIPE, 3, ASCII_DOT,
 	1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE,

    // --- 'C' (Offset 968) ---
 	1, ASCII_DOT, 1, ASCII_PIPE, 4, ASCII_SINGLE_QUOTE, 1, ASCII_COMMA,
 	2, ASCII_PIPE, 5, ASCII_SPACE, 2, ASCII_PIPE, 5, ASCII_SPACE,
 	2, ASCII_PIPE, 5, ASCII_SPACE, 1, ASCII_BACKTICK, 1, ASCII_PIPE,
 	4, ASCII_DOT, 1, ASCII_SINGLE_QUOTE,

    // --- 'D' (Offset 996) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 3, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_DOT, 1, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_DOT, 2, ASCII_PIPE, 3, ASCII_DOT,
 	1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE,

    // --- 'E' (Offset 1040) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 4, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE, 1, ASCII_DOT,
 	1, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SINGLE_QUOTE,
 	1, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	5, ASCII_SPACE, 1, ASCII_DOT, 2, ASCII_PIPE, 4, ASCII_DOT,
 	1, ASCII_PIPE,

    // --- 'F' (Offset 1082) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 4, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_SPACE, 2, ASCII_PIPE, 2, ASCII_SPACE, 1, ASCII_DOT,
 	2, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE,
 	1, ASCII_PIPE, 2, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	5, ASCII_SPACE, 1, ASCII_DOT, 2, ASCII_PIPE, 1, ASCII_DOT,
 	4, ASCII_SPACE,

    // --- 'G' (Offset 1124) ---
 	1, ASCII_DOT, 1, ASCII_PIPE, 5, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_DOT, 4, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE,
 	2, ASCII_PIPE, 2, ASCII_PIPE, 4, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_BACKTICK, 1, ASCII_PIPE, 4, ASCII_DOT, 1, ASCII_PIPE,
 	1, ASCII_SINGLE_QUOTE,

    // --- 'H' (Offset 1166) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_BACKTICK, 1, ASCII_SPACE, 2, ASCII_PIPE, 2, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	2, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_SPACE,
 	2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE,
 	1, ASCII_DOT, 2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_DOT,

    // --- 'I' (Offset 1216) ---
 	1, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE,
 	1, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE,
 	3, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE, 3, ASCII_SPACE,
 	2, ASCII_PIPE, 3, ASCII_SPACE, 1, ASCII_PIPE, 2, ASCII_DOT,
 	2, ASCII_PIPE, 2, ASCII_DOT, 1, ASCII_PIPE,

    // --- 'J' (Offset 1254) ---
 	1, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE,
 	1, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE,
 	3, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE, 3, ASCII_SPACE,
 	2, ASCII_PIPE, 3, ASCII_SPACE, 1, ASCII_SINGLE_QUOTE, 2, ASCII_DOT,
 	1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE, 3, ASCII_SPACE,

    // --- 'K' (Offset 1292) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_SLASH,
 	1, ASCII_SINGLE_QUOTE, 1, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE,
 	2, ASCII_SLASH, 2, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	2, ASCII_LESS_THAN, 3, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_SPACE, 2, ASCII_BACKSLASH, 2, ASCII_SPACE, 1, ASCII_DOT,
 	2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_BACKSLASH, 1, ASCII_DOT,

    // --- 'L' (Offset 1340) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 4, ASCII_SPACE, 1, ASCII_SPACE,
 	2, ASCII_PIPE, 4, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	4, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE, 4, ASCII_SPACE,
 	1, ASCII_DOT, 2, ASCII_PIPE, 3, ASCII_DOT, 1, ASCII_PIPE,

    // --- 'M' (Offset 1372) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 1, ASCII_BACKSLASH, 3, ASCII_SPACE,
 	1, ASCII_SLASH, 2, ASCII_PIPE, 1, ASCII_BACKTICK, 1, ASCII_SPACE,
 	2, ASCII_PIPE, 2, ASCII_BACKSLASH, 1, ASCII_DOT, 2, ASCII_SLASH,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	5, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_SPACE,
 	2, ASCII_PIPE, 5, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE,
 	1, ASCII_DOT, 2, ASCII_PIPE, 5, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_DOT,

    // --- 'N' (Offset 1430) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 1, ASCII_BACKSLASH, 3, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_BACKTICK, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	2, ASCII_BACKSLASH, 2, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE,
 	1, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE, 2, ASCII_BACKSLASH,
 	1, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_SPACE,
 	2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_BACKSLASH, 2, ASCII_PIPE,
 	1, ASCII_SPACE, 1, ASCII_DOT, 2, ASCII_PIPE, 3, ASCII_SPACE,
 	1, ASCII_BACKSLASH, 2, ASCII_PIPE, 1, ASCII_DOT,

    // --- 'O' (Offset 1492) ---
 	1, ASCII_DOT, 1, ASCII_PIPE, 4, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_COMMA, 2, ASCII_PIPE, 4, ASCII_SPACE, 2, ASCII_PIPE,
 	2, ASCII_PIPE, 4, ASCII_SPACE, 2, ASCII_PIPE, 2, ASCII_PIPE,
 	4, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_BACKTICK, 1, ASCII_PIPE,
 	4, ASCII_DOT, 1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE,

    // --- 'P' (Offset 1530) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 3, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_COMMA, 1, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_DOT,
 	1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	5, ASCII_SPACE, 1, ASCII_DOT, 2, ASCII_PIPE, 5, ASCII_SPACE,

    // --- 'Q' (Offset 1570) ---
 	1, ASCII_DOT, 1, ASCII_PIPE, 4, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_COMMA, 1, ASCII_SPACE, 2, ASCII_PIPE, 4, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 2, ASCII_PIPE, 4, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 2, ASCII_PIPE, 2, ASCII_SPACE,
 	2, ASCII_BACKSLASH, 2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_BACKTICK,
 	1, ASCII_PIPE, 4, ASCII_DOT, 1, ASCII_PIPE, 2, ASCII_BACKSLASH,

    // --- 'R' (Offset 1618) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 3, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_COMMA, 1, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_DOT,
 	1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_SPACE, 2, ASCII_BACKSLASH, 2, ASCII_SPACE, 1, ASCII_DOT,
 	2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_BACKSLASH, 1, ASCII_DOT,

    // --- 'S' (Offset 1666) ---
 	1, ASCII_DOT, 1, ASCII_PIPE, 3, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_SPACE, 2, ASCII_PIPE, 5, ASCII_SPACE, 1, ASCII_BACKTICK,
 	1, ASCII_PIPE, 3, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE, 1, ASCII_COMMA,
 	1, ASCII_SPACE, 1, ASCII_DOT, 3, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_SPACE, 1, ASCII_PIPE, 3, ASCII_DOT, 1, ASCII_PIPE,
 	1, ASCII_SINGLE_QUOTE,

    // --- 'T' (Offset 1708) ---
 	1, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE,
 	1, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE,
 	3, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE, 3, ASCII_SPACE,
 	2, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_SPACE, 1, ASCII_DOT,
 	2, ASCII_PIPE, 1, ASCII_DOT, 2, ASCII_SPACE,

    // --- 'U' (Offset 1746) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_BACKTICK, 1, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	3, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_SPACE,
 	2, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE,
 	1, ASCII_SPACE, 1, ASCII_BACKTICK, 1, ASCII_PIPE, 3, ASCII_DOT,
 	1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE, 1, ASCII_SPACE,

    // --- 'V' (Offset 1800) ---
 	2, ASCII_BACKSLASH, 6, ASCII_SPACE, 2, ASCII_SLASH, 1, ASCII_SPACE,
 	2, ASCII_BACKSLASH, 4, ASCII_SPACE, 2, ASCII_SLASH, 1, ASCII_SPACE,
 	2, ASCII_SPACE, 2, ASCII_BACKSLASH, 2, ASCII_SPACE, 2, ASCII_SLASH,
 	2, ASCII_SPACE, 3, ASCII_SPACE, 2, ASCII_BACKSLASH, 2, ASCII_SLASH,
 	3, ASCII_SPACE, 4, ASCII_SPACE, 1, ASCII_BACKSLASH, 1, ASCII_SLASH,
 	4, ASCII_SPACE,

    // --- 'W' (Offset 1842) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 6, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_BACKTICK, 1, ASCII_SPACE, 2, ASCII_PIPE, 6, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	2, ASCII_SPACE, 1, ASCII_SLASH, 1, ASCII_BACKSLASH, 2, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 2, ASCII_SPACE, 2, ASCII_BACKSLASH,
 	2, ASCII_SLASH, 2, ASCII_BACKSLASH, 2, ASCII_SLASH, 2, ASCII_SPACE,
 	3, ASCII_SPACE, 1, ASCII_BACKSLASH, 1, ASCII_SLASH, 2, ASCII_SPACE,
 	1, ASCII_BACKSLASH, 1, ASCII_SLASH, 3, ASCII_SPACE,

    // --- 'X' (Offset 1904) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_BACKSLASH, 2, ASCII_SPACE, 2, ASCII_SLASH,
 	1, ASCII_BACKTICK, 2, ASCII_SPACE, 2, ASCII_BACKSLASH, 2, ASCII_SLASH,
 	2, ASCII_SPACE, 3, ASCII_SPACE, 1, ASCII_GREATER_THAN, 1, ASCII_LESS_THAN,
 	3, ASCII_SPACE, 2, ASCII_SPACE, 2, ASCII_SLASH, 2, ASCII_BACKSLASH,
 	2, ASCII_SPACE, 1, ASCII_DOT, 2, ASCII_SLASH, 2, ASCII_SPACE,
 	2, ASCII_BACKSLASH, 1, ASCII_DOT,

    // --- 'Y' (Offset 1948) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_BACKSLASH, 2, ASCII_SPACE, 2, ASCII_SLASH,
 	1, ASCII_BACKTICK, 2, ASCII_SPACE, 2, ASCII_BACKSLASH, 2, ASCII_SLASH,
 	2, ASCII_SPACE, 3, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE,
 	3, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_SPACE,
 	1, ASCII_DOT, 2, ASCII_PIPE, 1, ASCII_DOT, 2, ASCII_SPACE,

    // --- 'Z' (Offset 1988) ---
 	1, ASCII_PIPE, 5, ASCII_SINGLE_QUOTE, 1, ASCII_SLASH, 4, ASCII_SPACE,
 	2, ASCII_SLASH, 1, ASCII_SPACE, 3, ASCII_SPACE, 2, ASCII_SLASH,
 	2, ASCII_SPACE, 2, ASCII_SPACE, 2, ASCII_SLASH, 3, ASCII_SPACE,
 	1, ASCII_SLASH, 5, ASCII_DOT, 1, ASCII_PIPE,

    // --- '[' (Offset 2018) ---
 	2, ASCII_PIPE, 3, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 3, ASCII_SPACE,
 	2, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE,
 	2, ASCII_PIPE, 3, ASCII_DOT,

    // --- '\' (Offset 2038) ---
 	2, ASCII_BACKSLASH, 4, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_BACKSLASH,
 	3, ASCII_SPACE, 2, ASCII_SPACE, 2, ASCII_BACKSLASH, 2, ASCII_SPACE,
 	3, ASCII_SPACE, 2, ASCII_BACKSLASH, 1, ASCII_SPACE, 4, ASCII_SPACE,
 	2, ASCII_BACKSLASH,

    // --- ']' (Offset 2064) ---
 	3, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_PIPE,
 	3, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_PIPE,
 	3, ASCII_DOT, 2, ASCII_PIPE,

    // --- '^' (Offset 2084) ---
 	2, ASCII_SPACE, 1, ASCII_DOT, 2, ASCII_SPACE, 1, ASCII_DOT,
 	1, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_PIPE, 1, ASCII_COMMA,
 	1, ASCII_PIPE, 3, ASCII_SPACE, 1, ASCII_PIPE,

    // --- '_' (Offset 2106) ---
	4, ASCII_DOT,

    // --- '`' (Offset 2106) ---
 	2, ASCII_BACKTICK, 2, ASCII_SPACE,

    // --- 'a' (Offset 2114) ---
 	1, ASCII_SPACE, 3, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE, 1, ASCII_DOT,
 	1, ASCII_SPACE, 1, ASCII_DOT, 1, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_BACKTICK, 1, ASCII_PIPE,
 	2, ASCII_DOT, 2, ASCII_PIPE, 1, ASCII_DOT,

    // --- 'b' (Offset 2144) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 4, ASCII_SPACE, 1, ASCII_SPACE,
 	2, ASCII_PIPE, 4, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	2, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE, 1, ASCII_COMMA, 1, ASCII_SPACE,
 	2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_DOT,
 	2, ASCII_PIPE, 2, ASCII_DOT, 1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE,

    // --- 'c' (Offset 2184) ---
 	1, ASCII_DOT, 1, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE, 1, ASCII_COMMA,
 	2, ASCII_PIPE, 3, ASCII_SPACE, 1, ASCII_BACKTICK, 1, ASCII_PIPE,
 	2, ASCII_DOT, 1, ASCII_SINGLE_QUOTE,

    // --- 'd' (Offset 2204) ---
 	4, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_BACKTICK, 4, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_DOT, 1, ASCII_PIPE,
 	2, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	2, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_BACKTICK,
 	1, ASCII_PIPE, 2, ASCII_DOT, 2, ASCII_PIPE, 1, ASCII_DOT,

    // --- 'e' (Offset 2244) ---
 	1, ASCII_DOT, 1, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_COMMA, 2, ASCII_PIPE, 2, ASCII_DOT, 2, ASCII_PIPE,
 	1, ASCII_BACKTICK, 1, ASCII_PIPE, 3, ASCII_DOT, 1, ASCII_SPACE,

    // --- 'f' (Offset 2268) ---
 	1, ASCII_SPACE, 1, ASCII_DOT, 1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE,
 	1, ASCII_SEMICOLON, 1, ASCII_SPACE, 2, ASCII_PIPE, 2, ASCII_SPACE,
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE, 1, ASCII_SPACE,
 	1, ASCII_SPACE, 2, ASCII_PIPE, 2, ASCII_SPACE, 1, ASCII_DOT,
 	2, ASCII_PIPE, 1, ASCII_DOT, 1, ASCII_SPACE,

    // --- 'g' (Offset 2306) ---
 	1, ASCII_DOT, 1, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_COMMA, 2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_BACKTICK, 1, ASCII_PIPE, 2, ASCII_DOT, 2, ASCII_PIPE,

    // --- 'h' (Offset 2330) ---
 	4, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_SPACE,
 	1, ASCII_BACKTICK, 2, ASCII_DOT, 1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE,
 	1, ASCII_SPACE, 1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 4, ASCII_SPACE,
 	1, ASCII_SPACE, 2, ASCII_PIPE, 4, ASCII_SPACE, 1, ASCII_SPACE,
 	2, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE, 1, ASCII_COMMA,
 	1, ASCII_SPACE, 2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_DOT, 2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_PIPE,

    // --- 'i' (Offset 2386) ---
 	1, ASCII_SPACE, 2, ASCII_SINGLE_QUOTE, 1, ASCII_SPACE, 1, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_SPACE, 1, ASCII_DOT, 2, ASCII_PIPE, 1, ASCII_DOT,

    // --- 'j' (Offset 2410) ---
 	3, ASCII_SPACE, 2, ASCII_SINGLE_QUOTE, 3, ASCII_SPACE, 2, ASCII_PIPE,
 	3, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_PIPE,

    // --- 'k' (Offset 2426) ---
 	3, ASCII_SPACE, 2, ASCII_PIPE, 2, ASCII_SPACE, 1, ASCII_BACKTICK,
 	2, ASCII_DOT, 1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE, 2, ASCII_SPACE,
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 4, ASCII_SPACE, 1, ASCII_SPACE,
 	2, ASCII_PIPE, 4, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_SPACE, 2, ASCII_SLASH, 1, ASCII_BACKTICK, 1, ASCII_SPACE,
 	2, ASCII_PIPE, 2, ASCII_LESS_THAN, 2, ASCII_SPACE, 1, ASCII_DOT,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 2, ASCII_BACKSLASH, 1, ASCII_DOT,

    // --- 'l' (Offset 2482) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 1, ASCII_BACKTICK, 1, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE,
 	1, ASCII_DOT, 2, ASCII_PIPE, 1, ASCII_DOT,

    // --- 'm' (Offset 2512) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 1, ASCII_CLOSE_PAREN, 2, ASCII_COMMA,
 	1, ASCII_OPEN_PAREN, 1, ASCII_PIPE, 1, ASCII_COMMA, 1, ASCII_SPACE,
 	1, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_DOT,
 	2, ASCII_PIPE, 4, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_DOT,

    // --- 'n' (Offset 2552) ---
 	1, ASCII_BACKTICK, 2, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_COMMA, 1, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_PIPE,
 	2, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_DOT,
 	2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_DOT,

    // --- 'o' (Offset 2584) ---
 	1, ASCII_DOT, 1, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_COMMA, 2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_BACKTICK, 1, ASCII_PIPE, 2, ASCII_DOT, 1, ASCII_PIPE,
 	1, ASCII_SINGLE_QUOTE,

    // --- 'p' (Offset 2610) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_COMMA, 1, ASCII_SPACE, 2, ASCII_PIPE, 2, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 2, ASCII_PIPE, 2, ASCII_DOT,
 	1, ASCII_PIPE, 1, ASCII_SINGLE_QUOTE,

    // --- 'q' (Offset 2638) ---
 	1, ASCII_SPACE, 2, ASCII_PIPE, 4, ASCII_SPACE, 1, ASCII_DOT,
 	2, ASCII_PIPE, 4, ASCII_SPACE, 7, ASCII_SPACE, 7, ASCII_SPACE,
 	1, ASCII_DOT, 1, ASCII_PIPE, 2, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE,
 	1, ASCII_BACKTICK, 2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_SPACE, 1, ASCII_BACKTICK, 1, ASCII_PIPE, 2, ASCII_DOT,
 	2, ASCII_PIPE, 1, ASCII_SPACE,

    // --- 'r' (Offset 2682) ---
 	4, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_COMMA,
 	4, ASCII_SPACE, 2, ASCII_PIPE, 1, ASCII_BACKTICK, 1, ASCII_SPACE,
 	8, ASCII_SPACE, 8, ASCII_SPACE, 1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE,
 	2, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE, 2, ASCII_SPACE, 1, ASCII_SPACE,
 	2, ASCII_PIPE, 5, ASCII_SPACE, 1, ASCII_DOT, 2, ASCII_PIPE,
 	1, ASCII_DOT, 4, ASCII_SPACE,

    // --- 's' (Offset 2726) ---
 	1, ASCII_OPEN_PAREN, 4, ASCII_SINGLE_QUOTE, 1, ASCII_SPACE, 1, ASCII_BACKTICK,
 	2, ASCII_SINGLE_QUOTE, 1, ASCII_CLOSE_PAREN, 1, ASCII_BACKTICK, 3, ASCII_DOT,
 	1, ASCII_SINGLE_QUOTE,

    // --- 't' (Offset 2744) ---
 	2, ASCII_SPACE, 2, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_SPACE,
 	2, ASCII_PIPE, 3, ASCII_SPACE, 2, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE,
 	2, ASCII_SINGLE_QUOTE, 1, ASCII_SPACE, 2, ASCII_SPACE, 2, ASCII_PIPE,
 	3, ASCII_SPACE, 2, ASCII_SPACE, 1, ASCII_BACKTICK, 1, ASCII_PIPE,
 	2, ASCII_DOT, 1, ASCII_SINGLE_QUOTE,

    // --- 'u' (Offset 2780) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_BACKTICK, 1, ASCII_SPACE, 2, ASCII_PIPE, 2, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE, 1, ASCII_SPACE, 1, ASCII_BACKTICK,
 	1, ASCII_PIPE, 2, ASCII_DOT, 1, ASCII_SINGLE_QUOTE, 1, ASCII_PIPE,
 	1, ASCII_DOT,

    // --- 'v' (Offset 2814) ---
 	2, ASCII_BACKSLASH, 2, ASCII_SPACE, 2, ASCII_SLASH, 1, ASCII_SPACE,
 	2, ASCII_BACKSLASH, 2, ASCII_SLASH, 1, ASCII_SPACE, 2, ASCII_SPACE,
 	1, ASCII_BACKSLASH, 1, ASCII_SLASH, 2, ASCII_SPACE,

    // --- 'w' (Offset 2836) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_BACKSLASH, 4, ASCII_SPACE, 2, ASCII_SLASH,
 	1, ASCII_BACKTICK, 2, ASCII_SPACE, 2, ASCII_BACKSLASH, 1, ASCII_SLASH,
 	1, ASCII_BACKSLASH, 2, ASCII_SLASH, 2, ASCII_SPACE, 3, ASCII_SPACE,
 	1, ASCII_BACKSLASH, 1, ASCII_SLASH, 1, ASCII_BACKSLASH, 1, ASCII_SLASH,
 	3, ASCII_SPACE,

    // --- 'x' (Offset 2870) ---
 	2, ASCII_BACKSLASH, 2, ASCII_SPACE, 2, ASCII_SLASH, 2, ASCII_SPACE,
 	1, ASCII_GREATER_THAN, 1, ASCII_LESS_THAN, 2, ASCII_SPACE, 2, ASCII_SLASH,
 	2, ASCII_SPACE, 2, ASCII_BACKSLASH,

    // --- 'y' (Offset 2890) ---
 	1, ASCII_SINGLE_QUOTE, 2, ASCII_PIPE, 2, ASCII_SPACE, 2, ASCII_PIPE,
 	1, ASCII_BACKTICK, 1, ASCII_SPACE, 1, ASCII_BACKTICK, 1, ASCII_PIPE,
 	2, ASCII_DOT, 2, ASCII_PIPE, 1, ASCII_SPACE, 5, ASCII_SPACE,
 	2, ASCII_PIPE, 1, ASCII_SPACE,

    // --- 'z' (Offset 2918) ---
 	2, ASCII_SPACE, 1, ASCII_COMMA, 2, ASCII_SPACE, 1, ASCII_PIPE,
 	1, ASCII_SINGLE_QUOTE, 3, ASCII_SPACE, 2, ASCII_SINGLE_QUOTE, 2, ASCII_SPACE,
 	7, ASCII_SPACE, 7, ASCII_SPACE, 3, ASCII_SINGLE_QUOTE, 1, ASCII_SLASH,
 	3, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_SLASH, 4, ASCII_SPACE,
 	1, ASCII_SLASH, 3, ASCII_DOT, 3, ASCII_SPACE,

    // --- '{' (Offset 2956) ---
 	2, ASCII_SPACE, 2, ASCII_OPEN_BRACE, 1, ASCII_SPACE, 2, ASCII_OPEN_BRACE,
 	1, ASCII_SPACE, 2, ASCII_OPEN_BRACE, 2, ASCII_SPACE, 1, ASCII_SPACE,
 	2, ASCII_OPEN_BRACE, 1, ASCII_SPACE, 2, ASCII_SPACE, 2, ASCII_OPEN_BRACE,

    // --- '|' (Offset 2980) ---
 	2, ASCII_PIPE, 2, ASCII_PIPE, 2, ASCII_PIPE, 2, ASCII_PIPE,
 	2, ASCII_PIPE,

    // --- '}' (Offset 2990) ---
 	2, ASCII_PIPE, 2, ASCII_SPACE, 4, ASCII_SPACE, 2, ASCII_CLOSE_BRACE,
 	2, ASCII_SPACE, 1, ASCII_SPACE, 2, ASCII_CLOSE_BRACE, 1, ASCII_SPACE,
 	2, ASCII_SPACE, 2, ASCII_CLOSE_BRACE, 1, ASCII_SPACE, 2, ASCII_CLOSE_BRACE,
 	1, ASCII_SPACE, 2, ASCII_CLOSE_BRACE, 2, ASCII_SPACE,

    // --- '~' (Offset 3020) ---
 	1, ASCII_SPACE, 1, ASCII_PERCENT, 1, ASCII_SPACE, 1, ASCII_PERCENT,
 	1, ASCII_PERCENT, 1, ASCII_SPACE, 1, ASCII_PERCENT, 1, ASCII_SPACE,

};
