name: Generate MkDocs documentation and publish
on:
  push:
    branches: [ "master", "develop" ]
    paths:
      - "Docs/**"
      - "!Docs/LikeC4/**"
      - "mkdocs.yml"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install LikeC4
        run: npm install -g likec4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build Site
        run: |
          pip install mkdocs-material mkdocs-likec4
          mkdocs build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4