name: Generate Doxygen documentation

on:
  push:
    branches: [ "develop", "master" ]
    paths:
      - 'App/**'
      - 'Core/**'
      - 'Docs/Doxyfile'
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: |
          sudo apt-get update -q
          sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen
        run: |
          cd Docs
          doxygen Doxyfile

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-html-${{ github.sha }}
          path: Docs/doxygen-output/html/
          retention-days: 7